### PR TITLE
Add eu-central-1 endpoints (Frankfurt region) for IAM and Route53

### PR DESCRIPTION
**Pull request by hjacobs**
The endpoints for IAM and Route53 for the eu-central-1 (Frankfurt) region are missing in endpoints.json. The fix is trivial as these services are region-independent.

### CODE REVIEW

**Comment by hjacobs** [comment]
Would be nice to get this merged and released soon, as we currently depend on a local workaround using the environment variable: BOTO_ENDPOINTS=/my/path/to/my/endpoints.json

**Comment by mrandi** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

**Comment by suzaku** [comment]
+1

**Comment by femueller** [comment]
+1

**Comment by jamesls** [comment]
Thanks!

**Pull request merged**
