### PR TITLE
Fix import path for ec2container connection

### PR DESCRIPTION
**Pull request by phobologic**
Also add new endpoints for ECS.

This is missing a test case, but the test case would mostly be that import works, and that seems a bit excessive.

### CODE REVIEW

**Comment by phobologic** [comment]
Not sure if there's anything else that is required for this.  Would love to see it in boto - we have to patch manually for the time being.

**Comment by klj613** [comment]
i need this

**Comment by nickrowlandboxuk** [comment]
+1

**Comment by jamesls** [comment]
Taking a look.

**Comment by jamesls** [comment]
Pulled in your PR and added a test for this .  Thanks for the PR.

**Comment by nickrowlandboxuk** [comment]
Thanks @phobologic @jamesls :+1:

**Comment by klj613** [comment]
Thanks :)

**Pull request merged**
