### PR TITLE
Python 2 / 3 compatibility fixes

### PR DESCRIPTION
**Pull request by catleeball**
@walkerjoe, Ed Hodapp, and I made several fixes to help boto be cross-compatible with Python 2 and 3. These issues were identified while working on making gsutil's py-six-current branch compatible with Python 2.7 and 3.5+. This was done under the guidance of @houglum

Notably, we're using the six library to help ensure byte strings vs unicode strings work together nicely. Many of the changes we made revolve around making Python 2 and Python 3's byte vs unicode strings play together nicely, along with changes in division.

Let us know if you have any questions about these changes! :slightly_smiling_face:

### CODE REVIEW

**Comment by houglum** [comment]
LGTM.  @mfschwartz, could you merge this when you get the chance?

**Review by mfschwartz — APPROVED** [review]

**Review by mfschwartz — COMMENTED** [review]
This is a giant diff, and I see no effective way to review it. Is it possible to provide a side-by-side diff instead?

**Review by mfschwartz — APPROVED** [review]

**Comment by houglum** [comment]
@mfschwartz Yeah, if you go to the "Files changed" tab, then the "Diff settings" button and click "Split", it should bring up a side-by-side diff.  The GitHub UI is... interesting. :upside_down_face:

**Review by mfschwartz — APPROVED** [review]

**Comment by catleeball** [comment]
@mfschwartz Matt beat me to it, you can see a screenshot of the split diff at go/github-split-diff if you need :)

**Pull request merged**
