### PR TITLE
Fixes boto/boto#2917 and updated dbinstance_class parameter comment and instance_class parameter name to dbinstance_class

### PR DESCRIPTION
**Pull request by ronaldosaheki**
Fixes boto/boto#2917 and updated `dbinstance_class` parameter comment and changed the `instance_class` parameter name in `restore_dbinstance_from_dbsnapshot`  to `dbinstance_class` to let the parameter name the same in both functions `restore_dbinstance_from_point_in_time` and `restore_dbinstance_from_dbsnapshot`

### CODE REVIEW

**Comment by danielgtaylor** [comment]
@ronaldosaheki thanks for the pull request. Typically new work will happen on the `rds2` module, which is code-generated rather than written by hand. If you still wish to make these changes to provide support for people using the `rds` module then you will need to add some unit tests that cover the new functionality. Aside from that, this change looks good to me :+1:

**Comment by ronaldosaheki** [comment]
Unit tests adjusted, it's just that most of the documentation use rds instead of rds2. At least for basic it should work.

**Comment by ronaldosaheki** [comment]
Added new unit test to cover added funcionality: restore a database snapshot from point in time to a new RDS instance into another VPC, specifying a subnetgroup and option-group from target VPC.

**Comment by ronaldosaheki** [comment]
@danielgtaylor Test to cover functionality added

**Pull request closed without merging**
