### PR TITLE
Update endpoints.json

### PR DESCRIPTION
**Pull request by JordonPhillips**
cc @kyleknap @jamesls

### CODE REVIEW

**Comment by kyleknap** [comment]
I think you need to update s3 to default to sigv4 as well.

**Comment by JordonPhillips** [comment]
Gotcha

**Comment by kyleknap** [comment]
It would also not hurt to add tests like this one: https://github.com/boto/boto/blob/develop/tests/unit/auth/test_sigv4.py#L553. Otherwise, looks good.

**Comment by JordonPhillips** [comment]
Done

**Comment by kyleknap** [comment]
:ship:

**Pull request merged**
