### PR TITLE
Resolve x-goog-storage-class header

### PR DESCRIPTION
**Pull request by peterlandry**
issue #3666
issue #3665

### CODE REVIEW

**Comment by atbaker** [comment]
Bumped into this problem myself today. Not sure why it just cropped up now, but this fix did the trick for me. I just confirmed it.

Thanks @peterlandry for putting together the PR. +1 on a merge from me.

**Comment by peterlandry** [comment]
It could have just shown up if you created a new bucket. They changed the bucket definitions, so `STANDARD` is no longer an option. Earlier in the pipeline, boto special-cases `STANDARD` and doesn't look for any storage class headers (https://github.com/boto/boto/blob/develop/boto/s3/key.py#L896) . It's only when it sees something else that it tries (and fails to resolve) the header. That's why manually setting the storage class to `STANDARD` "fixes" it.

**Comment by peterlandry** [comment]
And for reference, the new classes: https://cloud.google.com/storage/docs/storage-classes

**Comment by peterlandry** [comment]
Closing, https://github.com/boto/boto/pull/3691 has taken care of this!

**Pull request closed without merging**
