### PR TITLE
Fix for gsutil with dotted buckets

### PR DESCRIPTION
**Pull request by 7heo**
This PR is for solving the issue https://github.com/GoogleCloudPlatform/gsutil/issues/267. It only has been tested with `gsutil rsync` locally; but it passes the boto tests (at least the same commits in [another PR](https://github.com/boto/boto/pull/3155]) did), so it must work for every command.

### CODE REVIEW

**Comment by 7heo** [comment]
Fixes https://github.com/boto/boto/issues/2836.

**Comment by vlcinsky** [comment]
In short:
- **the more important case (ask for simple connect without specific region, get bucket and list) works - this is great**
- when using connect created by `boto.s3.connect_to_region(<region_name>)`, it fails.

We are testing boto-7theo_fix-for-gsutil-with-dotted-buckets branch:

    $ pwd
    ~/sandbox/botodoto/boto
    $ pip freeze
    -e git+https://github.com/boto/boto.git@d8c62b79f1c4f6dd856909241656e56933b39bee#egg=boto-7theo_fix-for-gsutil-with-dotted-buckets
    ipython==3.1.0
    py==1.4.27
    pytest==2.7.0

There are two tests (file `test_it.py` prescribes two test cases):
- test_boto_s3_connect_to_regions (failing)
- test_boto_connect (passing)

`test_it.py` has this content:

    import pytest


    @pytest.fixture
    def bucket_key_name():
        return ("cz-base.dp.ce-traffic.com", "region/cz/EventService.xml")


    def test_boto_s3_connect_to_region(bucket_key_name):
        """With boto.s3.connect_to_region we explicitly ask for given region"""
        bucket_name, key_name = bucket_key_name
        region = "eu-west-1"
        import boto.s3
        con = boto.s3.connect_to_region(region)
        bucket = con.get_bucket(bucket_name)
        assert bucket
        key = bucket.get_key(key_name)
        assert key


    def test_boto_connect(bucket_key_name):
        """In this case, we do not specify the region to connect to"""
        bucket_name, key_name = bucket_key_name
        import boto
        con = boto.connect_s3()
        bucket = con.get_bucket(bucket_name)
        assert bucket
        key = bucket.get_key(key_name)
        assert key

Let us run the test:

    $ py.test -vs --pdb test_it.py   ============================================================================================== test session starts ===============================================================================================
    platform linux2 -- Python 2.7.9 -- py-1.4.27 -- pytest-2.7.0 -- /home/javl/.virtualenvs/botodoto/bin/python2
    rootdir: /home/javl/sandbox/botodoto/boto, inifile:
    collected 2 items

    test_it.py::test_boto_s3_connect_to_region FAILED
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    bucket_key_name = ('cz-base.dp.ce-traffic.com', 'region/cz/EventService.xml')

        def test_boto_s3_connect_to_region(bucket_key_name):
            """With boto.s3.connect_to_region we explicitly ask for given region"""
            bucket_name, key_name = bucket_key_name
            region = "eu-west-1"
            import boto.s3
            con = boto.s3.connect_to_region(region)
    >       bucket = con.get_bucket(bucket_name)

    test_it.py:15:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    boto/s3/connection.py:520: in get_bucket
        return self.head_bucket(bucket_name, headers=headers, location=location)
    boto/s3/connection.py:539: in head_bucket
        response = self.make_request('HEAD', bucket_name, headers=headers, location=location)
    boto/s3/connection.py:682: in make_request
        retry_handler=retry_handler
    boto/connection.py:1071: in make_request
        retry_handler=retry_handler)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = S3Connection:s3-eu-west-1.amazonaws.com, request = <boto.connection.HTTPRequest object at 0x7fef9e626e90>, sender = None, override_num_retries = None, retry_handler = None

        def _mexe(self, request, sender=None, override_num_retries=None,
                  retry_handler=None):
            """
                mexe - Multi-execute inside a loop, retrying multiple times to handle
                       transient Internet errors by simply trying again.
                       Also handles redirects.

                This code was inspired by the S3Utils classes posted to the boto-users
                Google group by Larry Bates.  Thanks!

                """
            boto.log.debug('Method: %s' % request.method)
            boto.log.debug('Path: %s' % request.path)
            boto.log.debug('Data: %s' % request.body)
            boto.log.debug('Headers: %s' % request.headers)
            boto.log.debug('Host: %s' % request.host)
            boto.log.debug('Port: %s' % request.port)
            boto.log.debug('Params: %s' % request.params)
            response = None
            body = None
            ex = None
            if override_num_retries is None:
                num_retries = config.getint('Boto', 'num_retries', self.num_retries)
            else:
                num_retries = override_num_retries
            i = 0
            connection = self.get_http_connection(request.host, request.port,
                                                  self.is_secure)

            # Convert body to bytes if needed
            if not isinstance(request.body, bytes) and hasattr(request.body,
                                                               'encode'):
                request.body = request.body.encode('utf-8')

            while i <= num_retries:
                # Use binary exponential backoff to desynchronize client requests.
                next_sleep = min(random.random() * (2 ** i),
                                 boto.config.get('Boto', 'max_retry_delay', 60))
                try:
                    # we now re-sign each request before it is retried
                    boto.log.debug('Token: %s' % self.provider.security_token)
                    request.authorize(connection=self)
                    # Only force header for non-s3 connections, because s3 uses
                    # an older signing method + bucket resource URLs that include
                    # the port info. All others should be now be up to date and
                    # not include the port.
                    if 's3' not in self._required_auth_capability():
                        if not getattr(self, 'anon', False):
                            if not request.headers.get('Host'):
                                self.set_host_header(request)
                    boto.log.debug('Final headers: %s' % request.headers)
                    request.start_time = datetime.now()
                    if callable(sender):
                        response = sender(connection, request.method, request.path,
                                          request.body, request.headers)
                    else:
                        connection.request(request.method, request.path,
                                           request.body, request.headers)
                        response = connection.getresponse()
                    boto.log.debug('Response headers: %s' % response.getheaders())
                    location = response.getheader('location')
                    # -- gross hack --
                    # http_client gets confused with chunked responses to HEAD requests
                    # so I have to fake it out
                    if request.method == 'HEAD' and getattr(response,
                                                            'chunked', False):
                        response.chunked = 0
                    if callable(retry_handler):
                        status = retry_handler(response, i, next_sleep)
                        if status:
                            msg, i, next_sleep = status
                            if msg:
                                boto.log.debug(msg)
                            time.sleep(next_sleep)
                            continue
                    if response.status in [500, 502, 503, 504]:
                        msg = 'Received %d response.  ' % response.status
                        msg += 'Retrying in %3.1f seconds' % next_sleep
                        boto.log.debug(msg)
                        body = response.read()
                        if isinstance(body, bytes):
                            body = body.decode('utf-8')
                    elif response.status < 300 or response.status >= 400 or \
                            not location:
                        # don't return connection to the pool if response contains
                        # Connection:close header, because the connection has been
                        # closed and default reconnect behavior may do something
                        # different than new_http_connection. Also, it's probably
                        # less efficient to try to reuse a closed connection.
                        conn_header_value = response.getheader('connection')
                        if conn_header_value == 'close':
                            connection.close()
                        else:
                            self.put_http_connection(request.host, request.port,
                                                     self.is_secure, connection)
                        if self.request_hook is not None:
                            self.request_hook.handle_request_data(request, response)
                        return response
                    else:
                        scheme, request.host, request.path, \
                            params, query, fragment = urlparse(location)
                        if query:
                            request.path += '?' + query
                        # urlparse can return both host and port in netloc, so if
                        # that's the case we need to split them up properly
                        if ':' in request.host:
                            request.host, request.port = request.host.split(':', 1)
                        msg = 'Redirecting: %s' % scheme + '://'
                        msg += request.host + request.path
                        boto.log.debug(msg)
                        connection = self.get_http_connection(request.host,
                                                              request.port,
                                                              scheme == 'https')
                        response = None
                        continue
                except PleaseRetryException as e:
                    boto.log.debug('encountered a retry exception: %s' % e)
                    connection = self.new_http_connection(request.host, request.port,
                                                          self.is_secure)
                    response = e.response
                    ex = e
                except self.http_exceptions as e:
                    for unretryable in self.http_unretryable_exceptions:
                        if isinstance(e, unretryable):
                            boto.log.debug(
                                'encountered unretryable %s exception, re-raising' %
                                e.__class__.__name__)
                            raise
                    boto.log.debug('encountered %s exception, reconnecting' %
                                   e.__class__.__name__)
                    connection = self.new_http_connection(request.host, request.port,
                                                          self.is_secure)
                    ex = e
                time.sleep(next_sleep)
                i += 1
            # If we made it here, it's because we have exhausted our retries
            # and stil haven't succeeded.  So, if we have a response object,
            # use it to raise an exception.
            # Otherwise, raise the exception that must have already happened.
            if self.request_hook is not None:
                self.request_hook.handle_request_data(request, response, error=True)
            if response:
                raise BotoServerError(response.status, response.reason, body)
            elif ex:
    >           raise ex
    E           gaierror: [Errno -2] Name or service not known

    boto/connection.py:1030: gaierror

Now let us check, what request exactly was done:

    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    > /home/javl/sandbox/botodoto/boto/boto/connection.py(1030)_mexe()
    -> raise ex
    (Pdb) ex
    gaierror(-2, 'Name or service not known')
    (Pdb) response
    (Pdb) request
    <boto.connection.HTTPRequest object at 0x7fef9e626e90>

This was expected, exception does not tell much, no response set yet.

But the request is here and we can look inside:

    (Pdb) request.url
    *** AttributeError: 'HTTPRequest' object has no attribute 'url'
    (Pdb) request.method
    'HEAD'
    (Pdb) request.protocol
    'https'
    (Pdb) request.host
    u's3-eu-west-1-eu-west-1.amazonaws.com'
    (Pdb) request.port
    443
    (Pdb) request.path
    '/cz-base.dp.ce-traffic.com/'
    (Pdb) request.headers
    {'Date': 'Mon, 18 May 2015 16:04:53 GMT', 'Content-Length': '0', 'Authorization': u'<misty weather here>', 'User-Agent': 'Boto/2.38.0 Python/2.7.9 Linux/3.16.0-4-amd64'}
    (Pdb) request.params
    {}
    (Pdb) request.body
    ''
    (Pdb) request.auth_path
    '/cz-base.dp.ce-traffic.com/'

Hope this helps.

**Comment by vlcinsky** [comment]
Further researching the problem, I continued investigation of variables at the moment of failure:

    (Pdb) connection
    <httplib.HTTPSConnection instance at 0x7f7737c8ff80>
    (Pdb) dir(connection)
    (Pdb) connection.auto_open
    1
    (Pdb) connection.cert_file
    (Pdb) connection.connect
    <bound method HTTPSConnection.connect of <httplib.HTTPSConnection instance at 0x7f7737c8ff80>>
    (Pdb) connection.default_port
    443
    (Pdb) connection.host
    u's3-eu-west-1-eu-west-1.amazonaws.com'
    (Pdb) connection.port
    443
    (Pdb) connection.source_address
    (Pdb) connection.strict
    0
    (Pdb)

The value of `connection.host` seems wrong - there is the string **`eu-west-1`** repeated twice.

I would guess, that during creating connection to explicit region is the string inserted twice and not only once.

**Comment by 7heo** [comment]
@vlcinsky Thanks a flipping lot for doing all that research. I only used it with `gsutil` so far, so I will patch my patch to solve the problems you've found (Note: the unit tests should have picked that up...)

**Comment by 7heo** [comment]
@vlcinsky if you have time, I'd appreciate new testing. The last commit should solve your problem. It should even make it much better on average, as it respects the user-specified settings where my patch previously didn't.

**Comment by vlcinsky** [comment]
@7heo wonderfull, both tests are passing now:

    $ py.test -v test_it.py
    ============================================================================================== test session starts ===============================================================================================
    platform linux2 -- Python 2.7.9 -- py-1.4.27 -- pytest-2.7.0 -- /home/javl/.virtualenvs/botodoto/bin/python2
    rootdir: /home/javl/sandbox/botodoto/boto, inifile:
    collected 2 items

    test_it.py::test_boto_s3_connect_to_region PASSED
    test_it.py::test_boto_connect PASSED

    ============================================================================================ 2 passed in 1.45 seconds ============================================================================================

The test is done on following version:

    $ pip freeze
    -e git+https://github.com/boto/boto.git@2c0571a6c3c5c57bc9e2fdccef33c0fa50db27cf#egg=boto-7theo_fix-for-gsutil-with-dotted-buckets
    ipython==3.1.0
    py==1.4.27
    pytest==2.7.0

You made my day, now I can continue with couple of tasks, which I had to freeze for a moment.

Thanks a lot.

Now I hope to see it soon in released version.

**Comment by 7heo** [comment]
@vlcinsky you're welcome. I'm glad I helped at least someone ;)

**Comment by ryanbagwell** [comment]
@vlcinsky any update on this? Can this be merged?

**Comment by 7heo** [comment]
@ryanbagwell I'd rather refactor the connection class a bit more, to add accessors to the `host` variable, so it is possible to know whenever the host is set after the object creation (I know public accessors are a codesmell indicator; but it's the only way to keep the way it works while adding the needed functionality afaik).

**Comment by vlcinsky** [comment]
@7heo might have better ideas how to make the fix better, but I cannot estimate, when this would be completed and merged.

@ryanbagwell I am happily using this modification. I did some modification of `boto` test suite (buckets changed to use dots in names) and the number of failing tests did not change with this pull request. However, I did not manage to complete the test suite modifications so far it could be merged (and I am not sure, if I manage it in foreseeable future).

Personally, I would invite this modification being merged as current situation is bad - `boto` it is not at all usable for those having dots in bucket names and running latest Python 2.7.9 or newer (e.g. on Debian Jessie). I prefer significant improvement over waiting for perfect solution (which is of course welcome).

**Comment by savingschampion** [comment]
Is this happening ever?

**Comment by vlcinsky** [comment]
@savingschampion good question.
Personally I started to convert my scripts into boto3. It is not an easy step (see issue #3306), but it work and runs without problem for buckets with dots in names.

**Comment by xenithorb** [comment]
Is this ever going to get merged? I can't do backups with duplicity now because of this issue.

**Comment by 7heo** [comment]
@xenithorb Short answer: no. Long answer: not a chance sorry (also not my decision).

**Comment by 7heo** [comment]
Giving up.

**Pull request closed without merging**
