### PR TITLE
Fixed to make previous commit python3 safe

### PR DESCRIPTION
**Pull request by kopertop**
Sorry I hadn't updated my local checkout of boto to make the first commit through a pull-request.

This fix actually fixes my previous commit directly to boto/develop, which is intended to fix in some scenarios where Lists seem to come back from AWS as simple strings.

### CODE REVIEW

**Comment by kyleknap** [comment]
Can we get a test added to this PR for the previous commit that you added that tests the issue you fixed?

**Comment by kyleknap** [comment]
I was just thinking about this. Is this change: https://github.com/boto/boto/commit/059f525b8731556f4878cc46a7712f7c92f91940 even needed? Could you provide an example of how this edge case is entered? I am having trouble thinking of a way to reach this edge case.

**Comment by kopertop** [comment]
Yes, I ran across a very weird edge case that caused problems, let me see
if I can get an example together and build a test where you can see without
this check it fails.

On Mon, Jan 11, 2016 at 2:02 PM, Kyle Knapp <notifications@github.com>
wrote:

> I was just thinking about this. Is this change: 059f525
> <https://github.com/boto/boto/commit/059f525b8731556f4878cc46a7712f7c92f91940>
> even needed? Could you provide an example of how this edge case is entered?
> I am having trouble thinking of a way to reach this edge case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boto/boto/pull/3459#issuecomment-170653832>.
>



-- 
Chris Moyer

**Comment by kopertop** [comment]
I added a test which shows this failing, the problem is only when you do a full decode via the ```object_hook``` attribute of ```json.loads```

```
        dynamizer = types.Dynamizer()
        doc = '{"__type__":{"S":"Story"},"company_tickers":{"SS":["NASDAQ-TSLA","NYSE-F","NYSE-GM"]},"modified_at":{"N":"1452525162"},"created_at":{"N":"1452525162"},"version":{"N":"1"},"categories":{"SS":["AUTOMTVE","LTRTR","MANUFCTU","PN","PRHYPE","TAXE","TJ","TL"]},"provider_categories":{"L":[{"S":"F"},{"S":"GM"},{"S":"TSLA"}]},"received_at":{"S":"2016-01-11T11:26:31Z"}}'
        output_doc = {'provider_categories': ['F', 'GM', 'TSLA'], '__type__': 'Story', 'company_tickers': set(['NASDAQ-TSLA', 'NYSE-GM', 'NYSE-F']), 'modified_at': Decimal('1452525162'), 'version': Decimal('1'), 'received_at': '2016-01-11T11:26:31Z', 'created_at': Decimal('1452525162'), 'categories': set(['LTRTR', 'TAXE', 'MANUFCTU', 'TL', 'TJ', 'AUTOMTVE', 'PRHYPE', 'PN'])}
        self.assertEqual(json.loads(doc, object_hook=dynamizer.decode), output_doc)
```

Without this patch, the above tests fails with:

```
self = <boto.dynamodb.types.Dynamizer object at 0x10d2e29d0>, attr = ['F', 'GM', 'TSLA']

    def _decode_l(self, attr):
>       return [self.decode(i) for i in attr]

boto/dynamodb/types.py:377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <boto.dynamodb.types.Dynamizer object at 0x10d2e29d0>, attr = 'F'

    def decode(self, attr):
        """
            Takes the format returned by DynamoDB and constructs
            the appropriate python type.
    
            """
        if len(attr) > 1 or not attr:
            return attr
>       dynamodb_type = list(attr.keys())[0]
E       AttributeError: 'str' object has no attribute 'keys'

boto/dynamodb/types.py:338: AttributeError
```

**Comment by kyleknap** [comment]
Thanks @kopertop. That's an interesting use case. Have not seen it used with ``load`` or ``dump``. I was curious into why this was happening and it is because the ``loads`` function will actually decode the nested dictionaries first as opposed to how the dynamizer decodes out objects first and recurses in. So ``json.loads`` will decode ``{"S":"F"}``,``{"S":"GM"}``, and ``{"S":"TSLA"}`` before decoding ``"provider_categories":{"L":[{"S":"F"},{"S":"GM"},{"S":"TSLA"}]}``. As a result when ``json.loads`` gets to the ``provider_categories`` attribute the value will be ``"provider_categories":{"L":["F","M","TSLA"]}`` and that will cause the dynamizer to fail because that is not valid syntax. Now the check makes sense. Merging.

**Pull request merged**
