### PR TITLE
Add missing eu-central-1 region for S3 Website

### PR DESCRIPTION
**Pull request by krallin**
URL as per:

http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html

### CODE REVIEW

**Comment by krallin** [comment]
Ping? This is a rather simple fix, and without it, `get_website_endpoint` is broken for `eu-central-1`.

**Comment by pani-c** [comment]
Is this pull request in queue for merging?

**Comment by kyleknap** [comment]
Thanks! Merging.

**Comment by pani-c** [comment]
Thank you!

**Pull request merged**
