### PR TITLE
Add the option to require a password reset when creating/updating a login profile.

### PR DESCRIPTION
**Pull request by mtougeron**
Add the option to require a password reset when creating/updating a login profile. This fixes issue #2732 

The code is initially based on pr #2746 but I also added the password_reset_required param for when creating a login profile. I also added the missing unit tests.

### CODE REVIEW

**Comment by mtougeron** [comment]
This failed on the Python 3.4 build but from the Travis CI output (or lack of) it looks like it was a Travis CI error and not related to the code.

**Comment by mtougeron** [comment]
Hi, any update on this? Thanks, Mike.

**Comment by mtougeron** [comment]
Hi, any update on this? Thanks, Mike.

**Comment by wt** [comment]
Any chance this one can be merged? I, for one, would find it useful.

**Comment by krazykid** [comment]
+1 I would find this useful too.

**Pull request closed without merging**
