### PR TITLE
Support for wildcard in CloudFront invalidation paths

### PR DESCRIPTION
**Pull request by jogold**

### CODE REVIEW

**Comment by oba11** [comment]
+1

**Comment by kyleknap** [comment]
Can you add a test for this?

**Comment by landakram** [comment]
Hello! According to [this line](https://github.com/boto/boto/blob/develop/boto/cloudfront/invalidation.py#L74) it looks like boto correctly supports wildcards. Should this issue be closed?

**Comment by jogoldwasser** [comment]
Yes, it is now supported. This issue should be closed.

On Mon, Nov 30, 2015 at 9:16 PM, Mark Hudnall <notifications@github.com>
wrote:

> Hello! According to this line
> <https://github.com/boto/boto/blob/develop/boto/cloudfront/invalidation.py#L74>
> it looks like boto correctly supports wildcards. Should this issue be
> closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boto/boto/pull/3195#issuecomment-160747977>.
>



-- 
Jonathan Goldwasser
jo@goldwasser.net

**Pull request closed without merging**
