### PR TITLE
Add the ability to delete a virtual mfa device

### PR DESCRIPTION
**Pull request by mtougeron**

### CODE REVIEW

**Comment by mtougeron** [comment]
This failed on the Python 3.4 build but from the Travis CI output (or lack of) it looks like it was a Travis CI error and not related to the code.

**Comment by jamesls** [comment]
Could you rebase against develop and re push you branch?  We had to fix an issue in our test deps that was causing the travis CI builds to hang.  Thanks.

**Comment by mtougeron** [comment]
sure thing. I'll do that now.

**Comment by mtougeron** [comment]
Ugh, I think I screwed up the rebase here and in PR #3007. Let me know if I need to redo this PR. :/

**Comment by mtougeron** [comment]
Hi, any update on this? Thanks, Mike

**Pull request closed without merging**
