### PR TITLE
Add support for encrypted EBS by KMS CMS Key

### PR DESCRIPTION
**Pull request by MisaKondo**
relative to #2769

### CODE REVIEW

**Comment by nishigori** [comment]
+1

**Comment by Bsami** [comment]
+1  I really need this and i hope this will be merged with the official release very soon

**Comment by kyleknap** [comment]
Thanks for the PR. Looks good. Merging

**Comment by Bsami** [comment]
Thanks.

**Comment by MisaKondo** [comment]
Thanks

**Pull request merged**
