### PR TITLE
Fixes JSON error parsing error when receiving bytes in Python 3.

### PR DESCRIPTION
**Pull request by codebyneil**
Should fix a couple errors:
https://github.com/boto/boto/issues/2681
https://github.com/boto/boto/issues/2677

That said, I had a bit of trouble with testing, so I'm not 100% on this... If you're going to try to test it, I suggest removing the try/except wrapping because I was getting a different TypeError in the testing framework than I was from the actual bug.

### CODE REVIEW

**Comment by tuxlife** [comment]
Hello @danielgtaylor,

is something missing, or can you please merge the pr?

many thanks,
Matthias

**Comment by StevenMapes** [comment]
Any word on when this is likely to be merged in as it's been almost a year and it fixes a very real bug

**Comment by mochawich** [comment]
will this be merged anytime soon❓
Thanks

**Comment by the-neil** [comment]
I don't even remember writing this anymore... 😛 Have you guys still been
seeing this error?

**Comment by mochawich** [comment]
Yes, using [Ansible - Rds module](http://docs.ansible.com/ansible/latest/rds_module.html) with Python 3 results in this error.

**Comment by baughj** [comment]
@nourchawich 👍 to that. Any reason why this cannot be merged?

**Pull request closed without merging**
