### PR TITLE
Fix incorrect handling of route tables containing propagatingVgwSet, add...

### LINKED ISSUE #3049: Incorrect boto.vpc.routetable.RouteTable objects with propagated routes
When investigating a boto.vpc.routetable.RouteTable object I noticed the following behaviour:

If the route table has route propagation enabled, we see 'half baked' route table objects being created, containing just tags. The behaviour is:

If no route propagation is enabled; create a correct route table object.
If route propagation _is_ enabled; create a route object with tags set to an empty dict ({}). Next, for each tag in the tagSet; create a route object containing no routes, and 'key' set to the key of the fist tag, 'value', set to the value of the first tag.

Ipython example:

Normal Route object:

```
In [7]: vars(all_route_tables[1].routes[2])
Out[7]:
{'destination_cidr_block': u'1.2.3.4/16',
 'gateway_id': u'vgw-123',
 'instance_id': None,
 'interface_id': None,
 'state': u'active',
 'vpc_peering_connection_id': None}
```

Route object with route propagation, notice tags are empty:

```
In [9]: vars(all_route_tables[1])
Out[9]:
{'associations': [RouteAssociation:rtbassoc-123],
 'connection': VPCConnection:ec2.us-east-1.amazonaws.com,
 'gatewayId': u'vgw-123',
 'id': u'rtb-123',
 'item': u'\n                ',
 'region': RegionInfo:us-east-1,
 'routes': [Route:1.2.3.4/17,
  Route:0.0.0.0/0,
  Route:1.2.3.5/16,],
 'tags': {},
 'vpc_id': u'vpc-123'}
```

The next Route object contains the tags of the previous one:

```
{'associations': [],
 'connection': VPCConnection:ec2.us-east-1.amazonaws.com,
 'id': None,
 'item': u'\n                ',
 'key': u'Foo',
 'region': RegionInfo:us-east-1,
 'routes': [],
 'tags': {},
 'value': u'Bar',
 'vpc_id': None}
```

And so on.

PR #3046 fixes this issue, and adds tests for it. PR #3047 contains the fix and adds a test for the route origin.

### PR DESCRIPTION
**Pull request by ojongerius**
... origin to Route objects.

Fixes #3049

### CODE REVIEW

**Comment by mtdowling** [comment]
This seems to be a duplicate of https://github.com/boto/boto/pull/3046. Should this one be closed?

**Comment by ojongerius** [comment]
@mtdowling this PR includes route origin. As both are related I'll close #3046 and will address your remarks in this one.

- [ ] Change propagating_vgws to propagatingvgws
- [ ]  Assert that propagating_vgws is actually populated
- [ ]  Rebase against the latest develop

**Comment by ojongerius** [comment]
@mtdowling have added tests. Good to merge?

**Comment by ojongerius** [comment]
Just noticed this has been open for a year. :weary:

**Comment by ojongerius** [comment]
Guess this is not happening.

**Pull request closed without merging**
