### PR TITLE
added support for eu-west-3 (Paris)

### PR DESCRIPTION
**Pull request by maishsk**
fix for #3783

Please review

### CODE REVIEW

**Review by szknitter — APPROVED** [review]
And that is much much better 👍

**Comment by 4ndr4s** [comment]
@maishsk when are you planning to merge this fix?

**Comment by maishsk** [comment]
@4ndr4s if I had merge permission - I would love to - but I do not have permissions to do so.

**Comment by maprager** [comment]
The following file - needs to be updated: 
/usr/local/lib/python2.7/dist-packages/boto/endooints.json 
I made a local change on my server - that seemed to cover the problem - but I am not sure, if all the services mentioned in the file (attached) are correct.
Someone should review.
[endpoints.zip](https://github.com/boto/boto/files/1898299/endpoints.zip)

**Comment by z0ph** [comment]
Need a merge! Please!

**Comment by erivni** [comment]
@maishsk 👍 💯

**Comment by maishsk** [comment]
@JordonPhillips @mfschwartz Can you help getting this merged please?

**Comment by julienmary** [comment]
I guess it won't be merged until all tests are validated, even if almost nobody is using python 2.6 and 3.3.

**Comment by z0ph** [comment]
Hello,

I think you can check with this config (told me by an AWS employee)

`[Boto]
use_endpoint_heuristics = True
`

> use_endpoint_heuristics:
> --
>   | Allows using endpoint heuristics to guess endpoints for regions that aren’t built in. This can also be specified with the BOTO_USE_ENDPOINT_HEURISTICS environment variable.


http://boto.cloudhackers.com/en/latest/boto_config_tut.html

**Comment by cameronbrunner** [comment]
For `eu-north-1`, which has a similar problem, I was able to get the `endpoints_path` setting to work and address my problem doing this https://github.com/boto/boto/issues/3842#issuecomment-563472466.  What is nice about `endponts_path` vs `use_endpoint_heuristics` is that `endpoints_path` will return the new Regions in `boto.ec2.regions()`

**Comment by rjouhann** [comment]
+1

**Comment by aaronkvanmeerten** [comment]
This one is affecting me for eu-west-3, eu-north-1, ap-east-1 and me-south-1

**Pull request closed without merging**
