### PR TITLE
added support for eu-west-3 (Paris)

### PR DESCRIPTION
**Pull request by maishsk**
This is to address #3783 

Please review

### CODE REVIEW

**Comment by maishsk** [comment]
recheck

**Comment by ttlequals0** [comment]
Is there an ETA on when this will be merged?

**Comment by ebarault** [comment]
hi, could someone please have a look? I guess it's preventing quite a few people from using the new aws datacenter in Paris

**Comment by canssens** [comment]
+1 needed

**Comment by nmozen** [comment]
+1 we also need this to use in our script and with ansible.

**Comment by szknitter** [comment]
It is about 40 lines or REAL changes...

Please commit it again after making changes in something, that will not affect lines endings.

**Comment by maishsk** [comment]
@szknitter I am not sure how to re-submit. 
Should I create a new PR ?

**Comment by szknitter** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
I have no idea :)
I suppose, that if you commit the file again, then id diff in pull request you will see all changes (not separate from commit 1 and commit 2).So if you pull the clean file (maybe into other directory) and then apply only your changes and commit it again, then there is a possibility, that only your lines will be changed. If no, then try to use some other file editor, that will not replace line endings (I suppose, that it is Linux vs Windows line endings problem).Good luck! :)

**Comment by maishsk** [comment]
Will submit a new PR shortly - with only the specific changes. 
Abandon PR

**Comment by maishsk** [comment]
Submitted https://github.com/boto/boto/pull/3794 to replace this one.

**Comment by abdulito** [comment]
Can you guys please release this?

**Comment by sternhenri** [comment]
+1^ 🙌

**Comment by tammytankian** [comment]
+1 please

**Comment by mstiri** [comment]
+1

**Pull request closed without merging**
